name: Daily builds of the Svelte Language Tools Beta

# For testing
on: push

# For production
# on:
#   schedule:
#     - cron: "0 4 * * *"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
          registry-url: "https://registry.npmjs.org"

      # Ensure everything is compiling
      - run: "yarn install"
      - run: "yarn build"

      # Lets us use one-liner JSON manipulations the package.json files
      - run: "npm install -g json"

      # Setup the environment
      - run: 'json -I -f packages/svelte-vscode/package.json -e "this.dependencies[\`svelte-language-server\`]=\`file:../language-server\`"'
      - run: 'json -I -f packages/svelte-vscode/package.json -e "this.version=\`99.0.0\`"'
      - run: 'json -I -f packages/svelte-vscode/package.json -e "this.preview=true"'

      # To deploy we need a node_modules folder which isn't in the yarn
      # So, remove the workspace
      - run: "rm package.json yarn.lock"

      # Re-run the yarn install outside of the workspace
      - run: |
         cd packages/language-server
         yarn install
         cd ..
        name: 'Setup language-server'

      # Re-run the  yarn install outside of the workspace
      - run: |
         cd packages/svelte-vscode
         yarn install
        name: 'setup svelte-vscode'

      - uses: orta/monorepo-deploy-nightly@master
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          VSCE_TOKEN: ${{ secrets.AZURE_PAN_TOKEN }}
